import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from "../components/Hero"
import Experience from "../components/Experience"
import Connect from "../components/Connect"
import Work from "../components/Work"
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hao Jie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Experience/>
      <Work/>
      <Connect/>
    
    </div>
  )
}

export default Home
